project_id = "wdishwyubgftrkjuaszk"

[functions.ai-assistant]
verify_jwt = false

[functions.identity-verify]
verify_jwt = false

[functions.stripe-wallet-topup]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.printful-sync-products]
verify_jwt = true

[functions.printful-create-order]
verify_jwt = true

[functions.bazik-webhook]
verify_jwt = false

